### ISSUE TITLE
Whether to support the layout of the specified node level?

### ISSUE THREAD

**Issue by hezhangqing** [Netflix/vizceral#71] opened 2017-05-24 04:50 UTC
Hey，On the layout of the node, I would like to specify the part of the node layout at the same level, whether to do？

**Comment by jrsquared** [comment] 2017-05-24 06:23
I am sorry, I do not understand the question.

**Comment by hezhangqing** [comment] 2017-05-24 08:54
Thank you very much for your reply @jrsquared   I repeat it ，Whether there is any attribute or any means to display a specified node under the same level, in other words, display them on the same line, vertically or horizontally? For example, the following figure, node1 node2 node3 at the same level.


![desc](https://cloud.githubusercontent.com/assets/24910773/26395057/8efdf8c8-40a1-11e7-95c2-9c4b6834363e.png)

**Comment by jrsquared** [comment] 2017-05-28 18:23
There is not currently a way to force a node to be a specific level in the layout, but I would happily review a PR that would allow for this!

**Comment by jrsquared** [comment] 2017-06-02 14:57
Since this is currently as designed, will close this issue. However, I would be happy to review a PR that adds this functionality.

**Closed by jrsquared** 2017-06-02 14:57 UTC
