### ISSUE TITLE
nodes lining up into two columns

### ISSUE THREAD

**Issue by jmart1** [Netflix/vizceral#84] opened 2017-08-18 20:25 UTC
I followed the instructions from [Getting-Started](https://github.com/Netflix/vizceral/wiki/Getting-Started#from-scratch), specifically the HTML/ES5 section.  

The problem is that my nodes at the region level, are lining up into two columns.  One column all the way to the left and one all the way to the right.  This causes a problem because all the nodes on the right column have connections with each other and its hard to tell where those connections are connecting to, due to everything overlapping in that one column.  Is there a way to force the nodes to cascade like in [this example](https://github.com/Netflix/vizceral/blob/master/vizceral-example.png)?

**Comment by jrsquared** [comment] 2017-08-18 20:33
The problem is the (rudimentary) layout algorithm that is built into vizceral just lays out the leaf nodes to the right, so if all of those have no dependencies, they will all be lined up on the right. You can either pass in position in the JSON as a part of the node data `position: { x: 100, y: 100 }` or write a new layout algorithm.

**Comment by jmart1** [comment] 2017-08-18 21:11
Thanks for getting back to me.  I have seen sample data where the nodes line up cascadingly like in the sample image of my original post.  Is it the data in the nodes section or the connections section that is used by the layout to either cascade it or to line up into two columns?  For example, [this data set](https://github.com/Netflix/vizceral-example/blob/master/src/sample_data.json) lines up cascadingly.  What is it about that sample data that leads to this?

**Comment by jrsquared** [comment] 2017-08-18 21:18
It's literally just the connections between the nodes. If you have nodes A, B, C, and D, and connections A->B, A->C, A->D, every node but A will on the right side. However, if you have connections A->B, B->C, and C->D, they will all be in a line, all in their own columns. I'm assuming your data set has a lot of 'leaf' nodes (i.e. nodes that aren't the source node in any connection), so those are lining up on the right.

**Comment by jmart1** [comment] 2017-08-18 21:28
My data does have A -> B-> C.

Here is the anonymized version of my data.  In my data for example I have, 'unknown' -> 'service-b' -> 'service-k'.  In fact 'service-b' talks to a few services.  I would imagine there is enough services talking to each other for the algorithm to make multiple columns. 
{
    "connections": [
        {
            "class": "normal",
            "metrics": {
                "danger": 300,
                "normal": 6300
            },
            "notices": [],
            "source": "unknown",
            "target": "Provision-VM"
        }
    ],
    "name": "edge",
    "nodes": [
        {
            "renderer": "region",
            "name": "unknown",
            "class": "normal"
        },
        {
            "class": "normal",
            "connections": [
                {
                    "metrics": {
                        "danger": 2654,
                        "normal": 11053,
                        "warning": 460
                    },
                    "source": "service-a",
                    "target": "service-b"
                },
                {
                    "metrics": {
                        "danger": 4,
                        "normal": 7794,
                        "warning": 119
                    },
                    "source": "unknown",
                    "target": "service-b"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 1452,
                        "warning": 0
                    },
                    "source": "service-c",
                    "target": "service-b"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 390,
                        "warning": 0
                    },
                    "source": "service-d",
                    "target": "service-b"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 115,
                        "warning": 0
                    },
                    "source": "service-e",
                    "target": "service-b"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 61,
                        "warning": 0
                    },
                    "source": "service-f",
                    "target": "service-b"
                },
                {
                    "metrics": {
                        "danger": 3,
                        "normal": 18378,
                        "warning": 11
                    },
                    "source": "unknown",
                    "target": "service-g"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 1399,
                        "warning": 0
                    },
                    "source": "service-h",
                    "target": "service-g"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 502,
                        "warning": 66
                    },
                    "source": "service-i",
                    "target": "service-g"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 98,
                        "warning": 0
                    },
                    "source": "service-b",
                    "target": "service-g"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 4,
                        "warning": 0
                    },
                    "source": "perceptor",
                    "target": "service-g"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 6390,
                        "warning": 0
                    },
                    "source": "service-j",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 5867,
                        "warning": 0
                    },
                    "source": "service-b",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 4481,
                        "warning": 0
                    },
                    "source": "service-l",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 1378,
                        "warning": 2
                    },
                    "source": "unknown",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 568,
                        "warning": 0
                    },
                    "source": "service-i",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 172,
                        "warning": 0
                    },
                    "source": "service-g",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 2,
                        "warning": 0
                    },
                    "source": "service-m",
                    "target": "service-k"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 6670,
                        "warning": 0
                    },
                    "source": "service-h",
                    "target": "service-j"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 3014,
                        "warning": 0
                    },
                    "source": "service-l",
                    "target": "service-j"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 1038,
                        "warning": 11
                    },
                    "source": "unknown",
                    "target": "service-j"
                },
                {
                    "metrics": {
                        "danger": 15,
                        "normal": 756,
                        "warning": 0
                    },
                    "source": "service-n",
                    "target": "service-j"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 5734,
                        "warning": 0
                    },
                    "source": "service-j",
                    "target": "service-l"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 1653,
                        "warning": 0
                    },
                    "source": "unknown",
                    "target": "service-l"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 192,
                        "warning": 0
                    },
                    "source": "service-e",
                    "target": "service-l"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 123,
                        "warning": 0
                    },
                    "source": "service-b",
                    "target": "service-l"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 10,
                        "warning": 0
                    },
                    "source": "service-o",
                    "target": "service-l"
                },
                {
                    "metrics": {
                        "danger": 940,
                        "normal": 3136,
                        "warning": 442
                    },
                    "source": "service-o",
                    "target": "service-a"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 2372,
                        "warning": 2
                    },
                    "source": "unknown",
                    "target": "service-a"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 132,
                        "warning": 0
                    },
                    "source": "service-p",
                    "target": "service-a"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 111,
                        "warning": 0
                    },
                    "source": "service-b",
                    "target": "service-a"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 31,
                        "warning": 0
                    },
                    "source": "service-q",
                    "target": "service-a"
                },
                {
                    "metrics": {
                        "danger": 195,
                        "normal": 3603,
                        "warning": 1061
                    },
                    "source": "unknown",
                    "target": "service-q"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 2404,
                        "warning": 0
                    },
                    "source": "unknown",
                    "target": "service-c"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 372,
                        "warning": 0
                    },
                    "source": "service-r",
                    "target": "service-c"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 160,
                        "warning": 0
                    },
                    "source": "service-s",
                    "target": "service-c"
                },
                {
                    "metrics": {
                        "danger": 0,
                        "normal": 92,
                        "warning": 0
                    },
                    "source": "service-t",
                    "target": "service-c"
                }
            ],
            "maxVolume": 50000,
            "name": "Provision-VM",
            "nodes": [
     		    {
                    "class": "normal",
                    "name": "unknown",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-a",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-r",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "perceptor",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-k",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-j",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-t",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-e",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-q",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-c",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-p",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-g",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-m",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "modelling",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "apphost-api",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-b",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-l",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-o",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-d",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-h",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-f",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-s",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-n",
                    "renderer": "focusedChild"
                },
                {
                    "class": "normal",
                    "name": "service-i",
                    "renderer": "focusedChild"
                }
            ],
            "renderer": "region"
        }
    ],
    "renderer": "global"
}

**Comment by benzvan** [comment] 2018-04-06 19:51
Curious what happened here...
In the example above I see "unknown -> service-f, service-f -> service-b" which appears to meet the requirement given above for laying them out in a line.

**Comment by benzvan** [comment] 2018-04-23 17:31
I suspect the problem is here:
https://github.com/Netflix/vizceral/blob/master/src/layouts/ltrTreeLayout/ranker.js#L57-L84

This forces any service that receives internet traffic to the first column. I would propose altering that to only move nodes that only receive internet traffic to the first column.

**Comment by jrsquared** [comment] 2018-04-23 18:14
That would probably work fine, happy to review a PR as long as it doesn't screw up the sample data in https://github.com/Netflix/vizceral-example

**Comment by jrsquared** [comment] 2018-04-27 17:40
npm link down the dependency tree. The hacky way to develop more easily is, after linking, change the imports to point the index source file instead of the root project so you get sources instead of built libraries.

**Comment by benzvan** [comment] 2018-04-27 17:54
Putzed with it long enough to get it working. Had a weird dependency file-not-found thing.

**Comment by benzvan** [comment] 2018-04-27 17:55
I also ended up pointing the dependencies in the package.json to the file instead of the url or version.

**Comment by benzvan** [comment] 2018-04-27 20:17
This checks out locally. https://github.com/Netflix/vizceral/pull/123

**Comment by jrsquared** [comment] 2018-05-10 22:01
Fixed in 4.6.1

**Closed by jrsquared** 2018-05-10 22:01 UTC
